# Generated by Django 5.0 on 2025-07-18 23:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LostItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('date_registered', models.DateTimeField(auto_now_add=True)),
                ('mcq_1_question', models.CharField(blank=True, max_length=200)),
                ('mcq_1_answer_correct', models.CharField(blank=True, max_length=100)),
                ('mcq_1_answer_incorrect_1', models.CharField(blank=True, max_length=100)),
                ('mcq_1_answer_incorrect_2', models.CharField(blank=True, max_length=100)),
                ('mcq_1_answer_incorrect_3', models.CharField(blank=True, max_length=100)),
                ('mcq_2_question', models.CharField(blank=True, max_length=200)),
                ('mcq_2_answer_correct', models.CharField(blank=True, max_length=100)),
                ('mcq_2_answer_incorrect_1', models.CharField(blank=True, max_length=100)),
                ('mcq_2_answer_incorrect_2', models.CharField(blank=True, max_length=100)),
                ('mcq_2_answer_incorrect_3', models.CharField(blank=True, max_length=100)),
                ('status', models.CharField(choices=[('Unclaimed', 'Unclaimed'), ('Claimed', 'Claimed'), ('Resolved', 'Resolved')], default='Unclaimed', max_length=20)),
                ('claim_code', models.CharField(blank=True, max_length=6, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Claim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.CharField(max_length=100)),
                ('answer_1', models.CharField(blank=True, max_length=100)),
                ('answer_2', models.CharField(blank=True, max_length=100)),
                ('is_verified', models.BooleanField(default=False)),
                ('otp_code', models.CharField(blank=True, max_length=6, null=True)),
                ('otp_used', models.BooleanField(default=False)),
                ('date_claimed', models.DateTimeField(auto_now_add=True)),
                ('lost_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='LostFound.lostitem')),
            ],
        ),
    ]
