# Generated by Django 5.0 on 2025-08-01 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LostFound', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VaultSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admin_password', models.CharField(default='555', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Vault Settings',
                'verbose_name_plural': 'Vault Settings',
            },
        ),
    ]
