# Generated by Django 5.0 on 2024-10-01 18:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('UserAccounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('transaction_type', models.IntegerField(choices=[(1, 'Deposite'), (2, 'Borrow'), (3, 'Return')], null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('balance_after_transaction', models.DecimalField(decimal_places=2, max_digits=10)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='UserAccounts.userlibraryaccount')),
            ],
        ),
    ]
