"""Added is_done in todo

Revision ID: 148ec80ce23c
Revises: 
Create Date: 2024-12-17 23:12:14.215589

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '148ec80ce23c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('todo', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_done', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('todo', schema=None) as batch_op:
        batch_op.drop_column('is_done')

    # ### end Alembic commands ###
